VERBOSE: True

MODEL:
  SESSION: 'SRD'
  INPUT: 'shadow'
  TARGET: 'shadow_free'

# Optimization arguments.
OPTIM:
  BATCH_SIZE: 16
  NUM_EPOCHS: 200
  LR_INITIAL: 2e-4
  LR_MIN: 1e-6
  SEED: 3407
  WANDB: False
  MIXED_PRECISION: True
  GRAD_ACCUM_STEPS: 1
  WEIGHT_DECAY: 0.0

TRAINING:
  VAL_AFTER_EVERY: 2
  RESUME: False
  PS_W: 256
  PS_H: 256
  TRAIN_DIR: 'data/SRD/train/' # path to training data
  VAL_DIR: 'data/SRD/test/'     # path to validation data
  SAVE_DIR: 'checkpoints/'          # path to save models and images
  ORI: False

TESTING:
  WEIGHT: './checkpoints/SRD_epoch_86.pth'
  SAVE_IMAGES: True